services:

  fast-api-server:
    build: 
      context: .
      dockerfile: fast-api.Dockerfile
    volumes:
      - ./:/src    
    expose:
       - "7777-7779:80"
    deploy:
      replicas: 3

    restart:
      "always"
    networks:
      - network1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fast-api-server
     
    ports:
      - 7800:7800
    networks:
      - network1
    
# Yhdistetään samaan verkkoon rabbitMQ:n kanssa
networks:
  network1:
    name: distributedsystem
    external: true
  